# Generated by Django 4.2.3 on 2023-08-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
