# Generated by Django 4.2.3 on 2023-08-22 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequestForm',
            fields=[
                ('transection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transection')),
            ],
            bases=('transactions.transection',),
        ),
        migrations.AlterField(
            model_name='transection',
            name='transection_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Withdrawal'), (3, 'Loan'), (4, 'Loan Paid')]),
        ),
    ]
