# Generated by Django 4.2.3 on 2023-08-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_loanrequestform_alter_transection_transection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transection',
            name='transection_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Withdrawal'), (3, 'Loan'), (4, 'Loan Paid')], null=True),
        ),
        migrations.DeleteModel(
            name='LoanRequestForm',
        ),
    ]
